name: Interval Action checking for Blockly updates

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  updatePackages:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.PAT }}@github.com/$GITHUB_REPOSITORY
      - name: update packages
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: action@github.com
          AUTHOR_NAME: GitHub Action
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.PAT }}
          LOG_LEVEL: debug
          UPDATE_COMMAND: yarn
        with:
          args: upgrade blockly --latest